spring.application.name=stories
# ======================
# Database (PostgreSQL)
# ======================
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.show-sql=true

# ======================
# JWT Configuration
# ======================
jwt-secret=${JWT_SECRET_KEY}
jwt-expiration-ms=86400000

# ======================
# Gmail SMTP
# ======================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MY_EMAIL}
spring.mail.password=${API_KEY}
spring.mail.protocol=smtp
#spring.mail.properties.mail.debug=true
#logging.level.org.springframework.mail=DEBUG
#logging.level.com.sun.mail=DEBUG

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.default-encoding=UTF-8
spring.mail.from=${MY_EMAIL}

# ========================
# Cloudinry
# ========================
cloudinary.cloud_name=${API_CLOUDNAME}
cloudinary.api_key=${CLOUDINARY_KEY}
cloudinary.api_secret=${API_SECRET}



# ======================
# Application Base URL
# ======================
site.base.url.https=http://localhost:8080



server.error.include-message=always
